package com.mulesoft.muleexamplejdbcee;

import org.apache.commons.dbutils.QueryRunner;
import org.mule.api.context.notification.MuleContextNotificationListener;
import org.mule.context.notification.MuleContextNotification;
import org.mule.transport.jdbc.JdbcConnector;

public class SetupDatabaseNotificationListener implements
        MuleContextNotificationListener<MuleContextNotification> {

	public void onNotification(MuleContextNotification notification) {
		if (notification.getAction() == MuleContextNotification.CONTEXT_STARTED)
        {
			JdbcConnector jdbcFlightsConnector = (JdbcConnector)notification.getMuleContext().getRegistry().lookupConnector("jdbcFlightsConnector");

            try
	        {
	            deleteFlightsTable(jdbcFlightsConnector);
	        }
	        catch (Exception e)
	        {
	            try {
					createFlightsTable(jdbcFlightsConnector);
				} catch (Exception e1) {
					e1.printStackTrace();
				}
	        }

	        try {
				populateFlightsTable(jdbcFlightsConnector);
			} catch (Exception e) {
				e.printStackTrace();
			}	        

        }
	}
	
	protected void createFlightsTable(JdbcConnector jdbcConnector) throws Exception
    {
        QueryRunner qr = jdbcConnector.getQueryRunner();
        qr.update(jdbcConnector.getConnection(), "CREATE TABLE Flights(FLIGHT_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0)  NOT NULL PRIMARY KEY,ORIGIN VARCHAR(255),DESTINATION VARCHAR(255))");
    }
    
    protected void deleteFlightsTable(JdbcConnector jdbcConnector) throws Exception
    {
        QueryRunner qr = jdbcConnector.getQueryRunner();
        qr.update(jdbcConnector.getConnection(), "DELETE FROM Flights");
    }
    
    protected void populateFlightsTable(JdbcConnector jdbcConnector) throws Exception
    {
        QueryRunner qr = jdbcConnector.getQueryRunner();
        int updated;
        updated = qr.update(jdbcConnector.getConnection(), "INSERT INTO Flights(ORIGIN, DESTINATION) VALUES ('SFO', 'KOA')");
        updated = qr.update(jdbcConnector.getConnection(), "INSERT INTO Flights(ORIGIN, DESTINATION) VALUES ('SFO', 'LAX')");
        updated = qr.update(jdbcConnector.getConnection(), "INSERT INTO Flights(ORIGIN, DESTINATION) VALUES ('SFO', 'JFK')");
        updated = qr.update(jdbcConnector.getConnection(), "INSERT INTO Flights(ORIGIN, DESTINATION) VALUES ('SFO', 'LGA')");

    }
}
